f = open(r'C:\Users\alima\Dropbox\Meridia\integra-core\load_ffiec.py', encoding='utf-8')
content = f.read()
f.close()
content = content.replace('\u2713', 'OK')
content = content.replace('\u2717', 'FAIL')
content = content.replace('\u2500', '-')
g = open(r'C:\Users\alima\Dropbox\Meridia\integra-core\load_ffiec.py', 'w', encoding='utf-8')
g.write(content)
g.close()
print('Unicode symbols replaced')
