f = open(r'C:\Users\alima\Dropbox\Meridia\integra-core\load_ffiec.py')
content = f.read()
f.close()
content = content.replace('DB_USER = "postgres"', 'DB_USER = "meridia"')
content = content.replace('DB_PASS = "Aletheia2026##"', 'DB_PASS = "Ethanj2020##"')
g = open(r'C:\Users\alima\Dropbox\Meridia\integra-core\load_ffiec.py', 'w')
g.write(content)
g.close()
print('Credentials updated — user=meridia port=5433')
